apiVersion: v1
kind: Service
metadata:
  name: workshop-app-service
  namespace: production
spec:
  selector:
    app: workshop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
